version: "3"

services: 
    development:
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        ports:
            - "5000:5000"
        env_file: ".env"
    test:
        build:
            context: .
            dockerfile: Dockerfile
            target: test
        env_file: ".env.test"
        volumes:
            - ./todo_app:/todo-app/todo_app
