version: "3"

services: 
    development:
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        ports:
            - "5000:5000"
        env_file: ".env"
    test:
        build:
            context: .
            dockerfile: Dockerfile
            target: test
        env_file: ".env.test"
        command: tests
        volumes:
            - ./todo_app:/todo-app/todo_app
    test_e2e:
        image: devops-course-starter_test
        env_file: ".env"
        command: tests_e2e
        volumes:
            - ./todo_app:/todo-app/todo_app