@startuml code
allow_mixing

class todo_app.app {
    app
    create_app()
    ViewModel index()
    add_todo_item()
    start_todo_item(id)
    complete_todo_item(id)
    reset_todo_item(id)
    delete_todo_item(id)
}

class todo_app.ViewModel {
    items()
    todo_items()
    doing_items()
    done_items()
}

class todo_app.Config {
    
}

todo_app.app ..> todo_app.ViewModel :creates
todo_app.app <.. todo_app.Config :configures



class todo_app.data.session_items {
    Map get_lists()
    List get_items()
    Item get_item(id)
    add_item(title, description)
    Item save_item(id, list)
    delete_item(id)
}

class todo_app.data.Item {
    id
    name
    desc
    idList
    listNane
}

todo_app.app <---right---> todo_app.data.session_items:uses

todo_app.data.session_items ..> todo_app.data.Item:creates

@enduml