name: To Do app CI/CD
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      TRELLO_SECRET_KEY: ${{ secrets.TRELLO_SECRET_KEY}}
      TRELLO_ACCOUNT_KEY: ${{ secrets.TRELLO_ACCOUNT_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      BOARD_ID: ${{ secrets.BOARD_ID }}
      TODO_LIST_ID: ${{ secrets.TODO_LIST_ID }}
      IN_PROGRESS_LIST_ID: ${{ secrets.IN_PROGRESS_LIST_ID }}
      DONE_LIST_ID: ${{ secrets.DONE_LIST_ID }}
        

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build --target test --tag todo-app:test .

      - name: Unit/Integration Test
        run: docker run --env-file .env.test todo-app:test tests
      
      - name: End to End Test
        run: |
          docker run \
            -e SECRET_KEY \
            -e TRELLO_ACCOUNT_KEY \
            -e TRELLO_SECRET_KEY \
            -e BOARD_ID \
            -e TODO_LIST_ID \
            -e IN_PROGRESS_LIST_ID \
            -e DONE_LIST_ID \
            todo-app:test tests_e2e

      - name: Send Slack notifiaction success
        uses: rtCamp/action-slack-notify@v2
        if: success()
        env:
          SLACK_CHANNEL: workshop-7-alerts-rich-sushma
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: ':rocket:'
          SLACK_TITLE: Build Success
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Send Slack notifiaction fail
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_CHANNEL: workshop-7-alerts-rich-sushma
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: ':cry:'
          SLACK_TITLE: Build Failure
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Send Slack notifiaction cancel
        uses: rtCamp/action-slack-notify@v2
        if: cancelled()
        env:
          SLACK_CHANNEL: workshop-7-alerts-rich-sushma
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: ':man-shrugging:'
          SLACK_TITLE: Build Cancelled
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}